// Generated by JFlex 1.9.2 http://jflex.de/  (tweaked for IntelliJ platform)
// source: LatexTokenMaker.flex

/*
 * 08/12/2025
 *
 * LatexTokenMaker.java - Scanner for LaTeX.
 *
 * This library is distributed under a modified BSD license. See the included
 * LICENSE file for details.
 */
package org.fife.ui.rsyntaxtextarea.modes;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;


/**
 * Scanner for LaTeX.<p>
 *
 * This implementation was created using <a href="https://www.jflex.de/">JFlex</a> 1.9.1.
 *
 * @author Mattia Marelli
 * @version 1.0
 *
 */

public class LatexTokenMaker extends AbstractJFlexTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

	/** lexical states */
  public static final int YYINITIAL = 0;
  public static final int EOL_COMMENT = 2;
  public static final int ENV = 4;
  public static final int OPT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non-negative integer
   */
  private static final int[] ZZ_LEXSTATE = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\23\0\1\1\1\3"+
    "\1\0\1\4\1\5\1\6\2\4\1\7\1\10\1\11"+
    "\1\4\1\12\1\13\1\14\1\15\12\16\1\17\1\3"+
    "\1\0\1\4\1\0\2\4\32\16\1\20\1\21\1\22"+
    "\1\0\1\13\1\0\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\16\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\3\16\1\51\1\0\1\52\1\4\u0181\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\4\7\1\10\1\2\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\16\1\21\12\16\4\0\15\16"+
    "\4\0\2\16\1\22\14\16\2\0\1\23\3\16\1\0"+
    "\1\24\6\16\1\25\1\0\1\26\5\16\2\0\6\16"+
    "\1\25\50\16\1\27\5\16";

  private static int [] zzUnpackAction() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\254\0\254\0\327"+
    "\0\254\0\u0102\0\254\0\u012d\0\u0158\0\u0183\0\u01ae\0\u01d9"+
    "\0\u01d9\0\254\0\254\0\254\0\254\0\254\0\254\0\254"+
    "\0\254\0\u0204\0\254\0\u022f\0\u025a\0\u0285\0\u02b0\0\u02db"+
    "\0\u0306\0\u0331\0\u035c\0\u0387\0\u03b2\0\u03dd\0\u0408\0\u0433"+
    "\0\u045e\0\u0489\0\u04b4\0\u04df\0\u050a\0\u0535\0\u0560\0\u058b"+
    "\0\u05b6\0\u05e1\0\u060c\0\u0637\0\u0662\0\u068d\0\u06b8\0\u06e3"+
    "\0\u070e\0\u0739\0\u0764\0\u078f\0\u0204\0\u07ba\0\u07e5\0\u0810"+
    "\0\u083b\0\u0866\0\u0891\0\u08bc\0\u08e7\0\u0912\0\u093d\0\u0968"+
    "\0\u0993\0\u09be\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0"+
    "\0\254\0\u0aeb\0\u0b16\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2\0\u0bed"+
    "\0\u0c18\0\254\0\u0c43\0\u0c6e\0\u0c99\0\u0cc4\0\u0cef\0\u0d1a"+
    "\0\u0a14\0\u0d45\0\u0d70\0\u0d9b\0\u0dc6\0\u0df1\0\u0e1c\0\254"+
    "\0\u0e47\0\u0e72\0\u0e9d\0\u0ec8\0\u0ef3\0\u0f1e\0\u0f49\0\u0f74"+
    "\0\u0f9f\0\u0fca\0\u0ff5\0\u1020\0\u104b\0\u1076\0\u10a1\0\u10cc"+
    "\0\u10f7\0\u1122\0\u114d\0\u1178\0\u11a3\0\u11ce\0\u11f9\0\u1224"+
    "\0\u124f\0\u127a\0\u12a5\0\u12d0\0\u12fb\0\u1326\0\u1351\0\u137c"+
    "\0\u13a7\0\u13d2\0\u13fd\0\u1428\0\u1453\0\u147e\0\u14a9\0\u14d4"+
    "\0\u0204\0\u14ff\0\u152a\0\u1555\0\u1580\0\u15ab";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\2\5\1\10\1\11\12\5\1\12"+
    "\27\5\2\13\2\14\1\7\25\14\1\15\1\14\1\16"+
    "\15\14\1\17\2\14\1\20\1\21\47\20\1\13\1\22"+
    "\1\23\1\6\10\23\1\24\5\23\1\13\1\23\1\25"+
    "\26\23\1\25\1\23\60\0\1\26\50\0\1\27\2\0"+
    "\1\27\1\30\1\31\1\0\1\27\1\32\2\0\1\32"+
    "\1\27\1\33\1\0\1\31\1\32\1\34\1\35\1\36"+
    "\1\37\5\32\1\40\1\32\1\41\1\32\1\42\1\32"+
    "\1\43\1\44\1\32\1\45\2\32\2\0\2\14\1\0"+
    "\25\14\1\0\1\14\1\0\15\14\1\0\2\14\33\0"+
    "\1\46\11\0\1\47\52\0\1\50\55\0\1\51\2\0"+
    "\51\20\15\0\1\32\2\0\1\32\4\0\26\32\15\0"+
    "\1\32\2\0\1\32\4\0\4\32\1\52\21\32\15\0"+
    "\1\32\2\0\1\32\4\0\7\32\1\53\16\32\15\0"+
    "\1\32\2\0\1\32\4\0\4\32\1\54\10\32\1\55"+
    "\10\32\15\0\1\32\2\0\1\32\4\0\14\32\1\56"+
    "\2\32\1\57\6\32\15\0\1\32\2\0\1\32\4\0"+
    "\1\60\25\32\15\0\1\32\2\0\1\32\4\0\4\32"+
    "\1\61\21\32\15\0\1\32\2\0\1\32\4\0\1\62"+
    "\25\32\15\0\1\32\2\0\1\32\4\0\4\32\1\63"+
    "\21\32\15\0\1\32\2\0\1\32\4\0\4\32\1\64"+
    "\16\32\1\65\2\32\15\0\1\32\2\0\1\32\4\0"+
    "\21\32\1\66\4\32\37\0\1\67\56\0\1\70\56\0"+
    "\1\71\55\0\1\72\15\0\1\32\2\0\1\32\4\0"+
    "\6\32\1\73\17\32\15\0\1\32\2\0\1\32\4\0"+
    "\1\74\25\32\15\0\1\32\2\0\1\32\4\0\5\32"+
    "\1\75\20\32\15\0\1\32\2\0\1\32\4\0\2\32"+
    "\1\76\23\32\15\0\1\32\2\0\1\32\4\0\3\32"+
    "\1\77\22\32\15\0\1\32\2\0\1\32\4\0\20\32"+
    "\1\100\5\32\15\0\1\32\2\0\1\32\4\0\1\32"+
    "\1\101\24\32\15\0\1\32\2\0\1\32\4\0\25\32"+
    "\1\102\15\0\1\32\2\0\1\32\4\0\6\32\1\103"+
    "\11\32\1\104\5\32\15\0\1\32\2\0\1\32\4\0"+
    "\5\32\1\105\6\32\1\106\11\32\15\0\1\32\2\0"+
    "\1\32\4\0\2\32\1\107\23\32\15\0\1\32\2\0"+
    "\1\32\4\0\1\32\1\110\24\32\15\0\1\32\2\0"+
    "\1\32\4\0\4\32\1\111\21\32\31\0\1\70\42\0"+
    "\1\112\74\0\1\113\25\0\1\114\51\0\1\32\2\0"+
    "\1\32\4\0\10\32\1\115\15\32\15\0\1\32\2\0"+
    "\1\32\4\0\16\32\1\116\7\32\15\0\1\32\2\0"+
    "\1\32\4\0\23\32\1\117\2\32\3\0\1\120\11\0"+
    "\1\32\2\0\1\32\4\0\26\32\1\121\14\0\1\32"+
    "\2\0\1\32\4\0\4\32\1\122\21\32\15\0\1\32"+
    "\2\0\1\32\4\0\4\32\1\123\21\32\15\0\1\32"+
    "\2\0\1\32\4\0\2\32\1\124\1\32\1\125\5\32"+
    "\1\126\13\32\15\0\1\32\2\0\1\32\4\0\4\32"+
    "\1\57\21\32\15\0\1\32\2\0\1\32\4\0\1\127"+
    "\21\32\1\130\3\32\3\0\1\131\11\0\1\32\2\0"+
    "\1\32\4\0\26\32\1\132\14\0\1\32\2\0\1\32"+
    "\4\0\4\32\1\133\21\32\15\0\1\32\2\0\1\32"+
    "\4\0\22\32\1\134\3\32\15\0\1\32\2\0\1\32"+
    "\4\0\16\32\1\135\2\32\1\136\4\32\15\0\1\32"+
    "\2\0\1\32\4\0\16\32\1\137\7\32\17\0\1\140"+
    "\54\0\1\112\24\0\1\70\11\0\2\141\1\114\7\141"+
    "\2\114\2\141\1\0\1\141\26\114\15\0\1\32\2\0"+
    "\1\32\4\0\14\32\1\77\11\32\15\0\1\32\2\0"+
    "\1\32\4\0\22\32\1\142\3\32\15\0\1\32\2\0"+
    "\1\32\4\0\13\32\1\143\12\32\3\0\1\120\47\0"+
    "\1\121\14\0\1\32\2\0\1\32\4\0\5\32\1\105"+
    "\20\32\15\0\1\32\2\0\1\32\4\0\12\32\1\77"+
    "\13\32\15\0\1\32\2\0\1\32\4\0\15\32\1\144"+
    "\10\32\15\0\1\32\2\0\1\32\4\0\14\32\1\145"+
    "\11\32\15\0\1\32\2\0\1\32\4\0\4\32\1\146"+
    "\21\32\15\0\1\32\2\0\1\32\4\0\6\32\1\147"+
    "\17\32\13\0\1\150\1\0\1\32\2\0\1\32\4\0"+
    "\26\32\3\0\1\131\47\0\1\132\14\0\1\32\2\0"+
    "\1\32\4\0\25\32\1\151\15\0\1\32\2\0\1\32"+
    "\4\0\10\32\1\152\15\32\15\0\1\32\2\0\1\32"+
    "\4\0\1\153\25\32\15\0\1\32\2\0\1\32\4\0"+
    "\4\32\1\64\16\32\1\154\2\32\15\0\1\32\2\0"+
    "\1\32\4\0\1\155\25\32\17\0\1\114\50\0\1\32"+
    "\2\0\1\32\4\0\4\32\1\156\21\32\15\0\1\32"+
    "\2\0\1\32\4\0\4\32\1\157\21\32\15\0\1\32"+
    "\2\0\1\32\4\0\13\32\1\160\7\32\1\161\2\32"+
    "\15\0\1\32\2\0\1\32\4\0\24\32\1\162\1\32"+
    "\15\0\1\32\2\0\1\32\4\0\14\32\1\163\11\32"+
    "\15\0\1\32\2\0\1\32\4\0\20\32\1\164\5\32"+
    "\15\0\1\32\2\0\1\32\4\0\2\32\1\165\1\32"+
    "\1\125\21\32\15\0\1\32\2\0\1\32\4\0\15\32"+
    "\1\166\10\32\15\0\1\32\2\0\1\32\4\0\20\32"+
    "\1\167\5\32\15\0\1\32\2\0\1\32\4\0\1\32"+
    "\1\170\24\32\15\0\1\32\2\0\1\32\4\0\2\32"+
    "\1\171\23\32\15\0\1\32\2\0\1\32\4\0\20\32"+
    "\1\130\5\32\15\0\1\32\2\0\1\32\4\0\14\32"+
    "\1\172\11\32\15\0\1\32\2\0\1\32\4\0\13\32"+
    "\1\173\12\32\15\0\1\32\2\0\1\32\4\0\14\32"+
    "\1\174\11\32\15\0\1\32\2\0\1\32\4\0\10\32"+
    "\1\175\15\32\15\0\1\32\2\0\1\32\4\0\6\32"+
    "\1\176\17\32\15\0\1\32\2\0\1\32\4\0\1\177"+
    "\25\32\15\0\1\32\2\0\1\32\4\0\15\32\1\200"+
    "\10\32\15\0\1\32\2\0\1\32\4\0\14\32\1\130"+
    "\11\32\15\0\1\32\2\0\1\32\4\0\1\127\25\32"+
    "\15\0\1\32\2\0\1\32\4\0\21\32\1\201\4\32"+
    "\15\0\1\32\2\0\1\32\4\0\11\32\1\202\14\32"+
    "\15\0\1\32\2\0\1\32\4\0\22\32\1\203\3\32"+
    "\15\0\1\32\2\0\1\32\4\0\1\204\25\32\15\0"+
    "\1\32\2\0\1\32\4\0\22\32\1\205\3\32\15\0"+
    "\1\32\2\0\1\32\4\0\20\32\1\206\5\32\15\0"+
    "\1\32\2\0\1\32\4\0\22\32\1\207\3\32\15\0"+
    "\1\32\2\0\1\32\4\0\16\32\1\210\7\32\15\0"+
    "\1\32\2\0\1\32\4\0\13\32\1\160\12\32\15\0"+
    "\1\32\2\0\1\32\4\0\4\32\1\64\21\32\15\0"+
    "\1\32\2\0\1\32\4\0\1\211\25\32\15\0\1\32"+
    "\2\0\1\32\4\0\2\32\1\212\23\32\15\0\1\32"+
    "\2\0\1\32\4\0\14\32\1\213\11\32\15\0\1\32"+
    "\2\0\1\32\4\0\4\32\1\214\21\32\15\0\1\32"+
    "\2\0\1\32\4\0\15\32\1\215\10\32\15\0\1\32"+
    "\2\0\1\32\4\0\7\32\1\75\16\32\15\0\1\32"+
    "\2\0\1\32\4\0\7\32\1\130\16\32\15\0\1\32"+
    "\2\0\1\32\4\0\6\32\1\216\17\32\15\0\1\32"+
    "\2\0\1\32\4\0\12\32\1\217\13\32\15\0\1\32"+
    "\2\0\1\32\4\0\3\32\1\75\22\32\15\0\1\32"+
    "\2\0\1\32\4\0\20\32\1\75\5\32\15\0\1\32"+
    "\2\0\1\32\4\0\14\32\1\220\11\32\15\0\1\32"+
    "\2\0\1\32\4\0\4\32\1\221\21\32\15\0\1\32"+
    "\2\0\1\32\4\0\1\222\25\32\15\0\1\32\2\0"+
    "\1\32\4\0\13\32\1\223\12\32\15\0\1\32\2\0"+
    "\1\32\4\0\21\32\1\224\4\32\15\0\1\32\2\0"+
    "\1\32\4\0\4\32\1\225\21\32\15\0\1\32\2\0"+
    "\1\32\4\0\21\32\1\221\4\32\15\0\1\32\2\0"+
    "\1\32\4\0\14\32\1\226\11\32\15\0\1\32\2\0"+
    "\1\32\4\0\22\32\1\75\3\32\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5590];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\3\11\1\1\1\11\1\1\1\11\6\1\10\11"+
    "\1\1\1\11\12\1\4\0\15\1\4\0\17\1\2\0"+
    "\4\1\1\0\1\11\7\1\1\0\1\11\5\1\2\0"+
    "\6\1\1\11\56\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */


	/**
	 * Constructor. This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public LatexTokenMaker() {
	}

    @Override
    public void addNullToken() {
        if(currentState >= 0) {
            super.addNullToken();
        } else {
            super.addToken(s.array, start, start - 1, currentState, start);
        }
    }

    protected void addNullToken(int value) {
        super.addToken(s.array, start, start - 1, value, start);
    }

    /**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
        // take care of the math mode
        if(currentState != 0) {
            super.setLanguageIndex(1);
        } else {
            super.setLanguageIndex(0);
        }

		super.addToken(s.array, s.offset + zzStartRead, s.offset + zzMarkedPos - 1, tokenType, start + zzStartRead);
	}

    private void addToken(int tokenType, int languageIndex) {
        super.setLanguageIndex(languageIndex);
        super.addToken(s.array, s.offset + zzStartRead, s.offset + zzMarkedPos - 1, tokenType, start + zzStartRead);
    }

    private void addHyperlinkToken(int tokenType) {
        super.setLanguageIndex(0); // Hyperlinks cannot be found into math blocks
		super.addToken(s.array, s.offset + zzStartRead, s.offset + zzMarkedPos - 1, tokenType, start + zzStartRead, true);
	}

	/**
	 * ${inheritDoc}
	 */
	@Override
	public String[] getLineCommentStartAndEnd(int languageIndex) {
		return new String[] { "%", null };
	}

    @Override
	public void yyclose() {
	}

	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *        <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	@Override
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {
        super.s = text;
        super.start = startOffset;

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

        int state = YYINITIAL;
        setLanguageIndex(0);
        currentState = 0;

		if(initialTokenType == STATE_OPT) {
            state = OPT;
        } else if (initialTokenType < -1) { // math mode
            currentState = (byte) initialTokenType;
        }

		s = text;

		try {
			reset(text, 0, text.count, state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return new TokenImpl();
		}

	}

    private void switchMath(byte type) {
        if(type == currentState) {
            currentState = 0;
        } else {
            currentState = type;
        }
    }

    private void addTokenStripWS(int tokenType) {
        // take care of the math mode
        if(currentState != 0) {
            super.setLanguageIndex(1);
        } else {
            super.setLanguageIndex(0);
        }

        String text = yytext().trim();
        int textL = yylength() - text.length();

        if(textL != 0) {
            textL = text.length();
            super.addToken(s.array, s.offset + zzStartRead, s.offset + zzStartRead + textL - 1, tokenType, start + zzStartRead);
            super.addToken(s.array, s.offset + zzStartRead + textL, s.offset + zzMarkedPos - 1, TokenTypes.WHITESPACE, start + zzStartRead + textL);
        } else {
            super.addToken(s.array, s.offset + zzStartRead, s.offset + zzMarkedPos - 1, tokenType, start + zzStartRead);
        }
    }

    byte currentState;
    static byte STATE_INLINE_MATH_1 = -2;
    static byte STATE_INLINE_MATH_2 = -3;
    static byte STATE_DISPLAY_MATH_1 = -4;
    static byte STATE_DISPLAY_MATH_2 = -5;
    static byte STATE_OPT = -1;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LatexTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos).toString();
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }  // fall though
            case 151: break;
            case EOL_COMMENT: {
              addNullToken(); return firstToken;
            }  // fall though
            case 152: break;
            case ENV: {
              addNullToken(); return firstToken;
            }  // fall though
            case 153: break;
            case OPT: {
              addNullToken(); return firstToken;
            }  // fall though
            case 154: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { addToken(Token.IDENTIFIER);
            }
          // fall through
          case 24: break;
          case 2:
            { addToken(Token.WHITESPACE);
            }
          // fall through
          case 25: break;
          case 3:
            { addNullToken(); return firstToken;
            }
          // fall through
          case 26: break;
          case 4:
            { addToken(Token.SEPARATOR, 1); switchMath(STATE_INLINE_MATH_1);
            }
          // fall through
          case 27: break;
          case 5:
            { addToken(Token.COMMENT_EOL); yybegin(EOL_COMMENT);
            }
          // fall through
          case 28: break;
          case 6:
            { addToken(Token.SEPARATOR);
            }
          // fall through
          case 29: break;
          case 7:
            { addToken(Token.COMMENT_EOL);
            }
          // fall through
          case 30: break;
          case 8:
            { addToken(Token.REGEX);
            }
          // fall through
          case 31: break;
          case 9:
            { addToken(Token.SEPARATOR); yybegin(YYINITIAL);
            }
          // fall through
          case 32: break;
          case 10:
            { addToken(Token.PREPROCESSOR);
            }
          // fall through
          case 33: break;
          case 11:
            { addToken(Token.OPERATOR);
            }
          // fall through
          case 34: break;
          case 12:
            { addToken(Token.SEPARATOR); yybegin(ENV);
            }
          // fall through
          case 35: break;
          case 13:
            { addToken(Token.SEPARATOR, 1); switchMath(STATE_DISPLAY_MATH_1);
            }
          // fall through
          case 36: break;
          case 14:
            { addToken(Token.FUNCTION);
            }
          // fall through
          case 37: break;
          case 15:
            { addToken(Token.SEPARATOR, 1); currentState = STATE_INLINE_MATH_2;
            }
          // fall through
          case 38: break;
          case 16:
            { addToken(Token.SEPARATOR, 1); currentState = 0;
            }
          // fall through
          case 39: break;
          case 17:
            { addToken(Token.SEPARATOR, 1); currentState = STATE_DISPLAY_MATH_2;
            }
          // fall through
          case 40: break;
          case 18:
            { addToken(Token.RESERVED_WORD);
            }
          // fall through
          case 41: break;
          case 19:
            { addHyperlinkToken(Token.COMMENT_EOL);
            }
          // fall through
          case 42: break;
          case 20:
            { yypushback(1); addTokenStripWS(Token.RESERVED_WORD); yybegin(ENV);
            }
          // fall through
          case 43: break;
          case 21:
            { addToken(Token.VARIABLE);
            }
          // fall through
          case 44: break;
          case 22:
            { yypushback(1); addTokenStripWS(Token.FUNCTION); yybegin(ENV);
            }
          // fall through
          case 45: break;
          case 23:
            { addToken(Token.RESERVED_WORD); yybegin(OPT);
            }
          // fall through
          case 46: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
